name: GitHub Actions Demo

on:
  push:
    branches: [ main ]
    paths-ignore: [ .github/** ]
  pull_request:
    branches: [ main ]

  schedule:
   - cron: '15 6 * * SUN'
  
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true
        description: "Which environment to deploy to"

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'The triggering event was ${{ github.event_name }}'
      - run: echo 'The branch that caused this event was ${{ github.ref }}'

      - uses: actions/checkout@v3.0.0
      - run: |
          echo 'Here is a list of the files in this directory...'
          tree
  Test:
    runs-on: ubuntu-latest
    needs: [ Build ]
    environment: Test
    if: github.event_name == 'workflow_dispatch'
    steps:
      - run: echo 'Testing...'

  Load_Test:
    runs-on: ubuntu-latest
    needs: [ Build ]
    environment: Load-Test
    if: github.event_name == 'workflow_dispatch'
    steps:
      - run: echo 'Load testing...'

  Prod:
    runs-on: ubuntu-latest
    needs: [ Test, Load_Test ]
    environment: 
      name: Production
      url: https://writeabout.net
    if: github.event.inputs.environment == 'Production'
    steps:
      - run: |
          echo 'Step 1 deploying'
          sleep 2
          echo 'Step 2 deploying'
          sleep 2
          echo 'Step 3 deploying'
          sleep 2
          echo 'Step 4 deploying'
          sleep 2
          echo 'Step 5 deploying'
    
